services:
  gamebot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./data:/app/data
